services:
  pc11-1:
    build: ./pc11-1
    container_name: pc11-1
    hostname: pc11-1
    tty: true
    stdin_open: true
    privileged: true
    networks:
      pc11net:
        ipv4_address: 10.1.11.101
  pc11-2:
    build: ./pc11-2
    container_name: pc11-2
    hostname: pc11-2
    tty: true
    stdin_open: true
    privileged: true
    networks:
      pc11net:
        ipv4_address: 10.1.11.102
  pc12-1:
    build: ./pc12-1
    container_name: pc12-1
    hostname: pc12-1
    tty: true
    stdin_open: true
    privileged: true
    networks:
      pc12net:
        ipv4_address: 10.1.12.101
  pc12-2:
    build: ./pc12-2
    container_name: pc12-2
    hostname: pc12-2
    tty: true
    stdin_open: true
    privileged: true
    networks:
      pc12net:
        ipv4_address: 10.1.12.102
  pc21-1:
    build: ./pc21-1
    container_name: pc21-1
    hostname: pc21-1
    tty: true
    stdin_open: true
    privileged: true
    networks:
      pc21net:
        ipv4_address: 10.2.21.101
  pc21-2:
    build: ./pc21-2
    container_name: pc21-2
    hostname: pc21-2
    tty: true
    stdin_open: true
    privileged: true
    networks:
      pc21net:
        ipv4_address: 10.2.21.102

  r01:
    build: ./r01
    container_name: r01
    hostname: r01
    privileged: true
    networks:
      net01:
        ipv4_address: 10.0.1.2
      net02:
        ipv4_address: 10.0.2.2
      net101:
        ipv4_address: 10.0.101.254
    depends_on:
      - "abr11"
      - "abr21"
      - "asbr01"
  r02:
    build: ./r02
    container_name: r02
    hostname: r02
    privileged: true
    networks:
      net03:
        ipv4_address: 10.0.3.2
      net04:
        ipv4_address: 10.0.4.2
      net102:
        ipv4_address: 10.0.102.254
    depends_on:
      - "abr12"
      - "abr22"
      - "asbr01"

  r11:
    build: ./r11
    container_name: r11
    hostname: r11
    privileged: true
    networks:
      net11:
        ipv4_address: 10.1.1.2
      net12:
        ipv4_address: 10.1.2.2
      pc11net:
        ipv4_address: 10.1.11.254
    depends_on:
      - "pc11-1"
      - "pc11-2"
      - "abr11"
      - "abr12"
  r12:
    build: ./r12
    container_name: r12
    hostname: r12
    privileged: true
    networks:
      net13:
        ipv4_address: 10.1.3.2
      net14:
        ipv4_address: 10.1.4.2
      pc12net:
        ipv4_address: 10.1.12.254
    depends_on:
      - "abr11"
      - "abr12"

  r21:
    build: ./r21
    container_name: r21
    hostname: r21
    privileged: true
    networks:
      net21:
        ipv4_address: 10.2.1.2
      net22:
        ipv4_address: 10.2.2.2
      pc21net:
        ipv4_address: 10.2.21.254
    depends_on:
      - "pc21-1"
      - "pc21-2"
      - "abr21"
      - "abr22"

  abr11:
    build: ./abr11
    container_name: abr11
    hostname: abr11
    privileged: true
    networks:
      net01:
        ipv4_address: 10.0.1.254
      net11:
        ipv4_address: 10.1.1.254
      net13:
        ipv4_address: 10.1.3.254
  abr12:
    build: ./abr12
    container_name: abr12
    hostname: abr12
    privileged: true
    networks:
      net03:
        ipv4_address: 10.0.3.254
      net12:
        ipv4_address: 10.1.2.254
      net14:
        ipv4_address: 10.1.4.254
  abr21:
    build: ./abr21
    container_name: abr21
    hostname: abr21
    privileged: true
    networks:
      net02:
        ipv4_address: 10.0.2.254
      net21:
        ipv4_address: 10.2.1.254
  abr22:
    build: ./abr22
    container_name: abr22
    hostname: abr22
    privileged: true
    networks:
      net04:
        ipv4_address: 10.0.4.254
      net22:
        ipv4_address: 10.2.2.254

  asbr01:
    build: ./asbr01
    container_name: asbr01
    hostname: asbr01
    privileged: true
    networks:
      net101:
        ipv4_address: 10.0.101.2
      net102:
        ipv4_address: 10.0.102.2

networks:
  pc11net:
    ipam:
      config:
        - subnet: 10.1.11.0/24
  pc12net:
    ipam:
      config:
        - subnet: 10.1.12.0/24
  pc21net:
    ipam:
      config:
        - subnet: 10.2.21.0/24

  net01:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  net02:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  net03:
    ipam:
      config:
        - subnet: 10.0.3.0/24
  net04:
    ipam:
      config:
        - subnet: 10.0.4.0/24

  net11:
    ipam:
      config:
        - subnet: 10.1.1.0/24
  net12:
    ipam:
      config:
        - subnet: 10.1.2.0/24
  net13:
    ipam:
      config:
        - subnet: 10.1.3.0/24
  net14:
    ipam:
      config:
        - subnet: 10.1.4.0/24

  net21:
    ipam:
      config:
        - subnet: 10.2.1.0/24
  net22:
    ipam:
      config:
        - subnet: 10.2.2.0/24

  net101:
    ipam:
      config:
        - subnet: 10.0.101.0/24
  net102:
    ipam:
      config:
        - subnet: 10.0.102.0/24
