networks:
  vlan1001:
    driver: macvlan
    driver_opts:
      parent: ${VM1_IF}.1001
    ipam:
      config:
        - subnet: 10.1.1.0/24
          gateway: 10.1.1.1

services:
  pc1-1:
    image: alpine:latest
    container_name: pc1-1
    hostname: pc1-1
    tty: true
    stdin_open: true
    privileged: true
    networks:
      vlan1001:
        ipv4_address: 10.1.1.101
        mac_address: "02:42:ac:00:01:01"
  pc1-2:
    image: alpine:latest
    container_name: pc1-2
    hostname: pc1-2
    tty: true
    stdin_open: true
    privileged: true
    networks:
      vlan1001:
        ipv4_address: 10.1.1.102
        mac_address: "02:42:ac:00:01:02"

